# Generated by Django 3.2 on 2021-05-02 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.CharField(max_length=20)),
                ('descli', models.CharField(max_length=60)),
                ('citcli', models.CharField(max_length=60)),
                ('capcli', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Giornalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Titoli2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codtit2', models.CharField(max_length=250)),
                ('codslugtit2', models.SlugField(max_length=250, unique_for_date='codcreatedtit2')),
                ('codisintit2', models.CharField(max_length=250)),
                ('codbodytit2', models.TextField()),
                ('codpublishtit2', models.DateTimeField(default=django.utils.timezone.now)),
                ('codcreatedtit2', models.DateTimeField(auto_now_add=True)),
                ('codupdatedtit2', models.DateTimeField(auto_now=True)),
                ('codmintit2', models.FloatField()),
                ('codmaxtit2', models.FloatField()),
                ('codauthortit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_titoli2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
