# Generated by Django 3.1.7 on 2021-04-28 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codtit', models.CharField(max_length=250)),
                ('codslugtit', models.SlugField(max_length=250, unique_for_date='codcreatedtit')),
                ('codisintit', models.CharField(max_length=250)),
                ('codbodytit', models.TextField()),
                ('codpublishtit', models.DateTimeField(default=django.utils.timezone.now)),
                ('codcreatedtit', models.DateTimeField(auto_now_add=True)),
                ('codupdatedtit', models.DateTimeField(auto_now=True)),
                ('codmintit', models.FloatField()),
                ('codmaxtit', models.FloatField()),
                ('codauthortit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_titoli', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-codcreatedtit',),
            },
            managers=[
                ('codobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.CharField(max_length=250)),
                ('codslugcli', models.SlugField(max_length=250, unique_for_date='codpublishcli')),
                ('codbodycli', models.TextField()),
                ('codpublishcli', models.DateTimeField(default=django.utils.timezone.now)),
                ('codcreatedcli', models.DateTimeField(auto_now_add=True)),
                ('codupdatedcli', models.DateTimeField(auto_now=True)),
                ('codstatuscli', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('codauthorcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_clienti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-codpublishcli',),
            },
        ),
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(max_length=250)),
                ('codslug', models.SlugField(max_length=250, unique_for_date='codpublish')),
                ('codbody', models.TextField()),
                ('codpublish', models.DateTimeField(default=django.utils.timezone.now)),
                ('codcreated', models.DateTimeField(auto_now_add=True)),
                ('codupdated', models.DateTimeField(auto_now=True)),
                ('codstatus', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('codauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articolo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-codpublish',),
            },
        ),
    ]
